version: '3.7'

services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
           
        ports:
            - 27080:27017
        volumes:
            - ./mongo-init2.js:/docker-entrypoint-initdb.d/mongo-init2.js:ro